version: 2
updates:
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly

  - package-ecosystem: npm
    directory: /DragonglassApp/opencode
    schedule:
      interval: weekly

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly

  - package-ecosystem: pre-commit
    directory: /
    schedule:
      interval: weekly
    groups:
      pre-commit-hooks:
        patterns:
          - "*"
